# **Lab1: R Data Structures (20 points)**

#### **WRITE YOUR NAME HERE**


---
**Instructions**: Complete the lab below.
- <font color=red>Tasks</font> indicated in red must be completed to receive credit
- Include all code for your work
- Include markdown cells with written answers explaining your work when prompted
- Your completed lab must be submitted to Canvas as a pdf file by the end of the lab session
---



<br>




## Vectors and Matrices


####<font color=red>Task 1</font>  (1 point)

* Insert the number 5 at the end of `my_vector` in a code cell below WITHOUT using 1, 2, 3, or 4 in your code
* Print your output

Hint: Use the `c()` function.

In [ ]:
# vector defined
my_vector <- c(1, 2, 3, 4)

In [ ]:
# insert the number five in code below
my_vector <- c(1:5)
my_vector

[1] 1 2 3 4 5



<br>




#### <font color=red>Task 2</font>  (1 point)

* Insert a row  of `c(-1, -1)` at the top of `my_matrix`
* Print your output

Hint: Use the `rbind()` function.

In [ ]:
# matrix defined
my_matrix <- matrix(c(1,2,3,4,5,6), nrow = 3, ncol = 2, byrow=TRUE)
my_matrix

[,1] [,2]
[1,] 1    2   
[2,] 3    4   
[3,] 5    6

In [ ]:
# insert row
my_matrix <- rbind(c(-1,1), my_matrix)
my_matrix

[,1] [,2]
[1,] -1   1   
[2,]  1   2   
[3,]  3   4   
[4,]  5   6



<br>




#### <font color=red>Task 3</font>  (1 point)
* Print the length of `my_vector`

In [ ]:
# vector defined
my_vector <- c(1,3,5,3,2,5,6,7,8,9,3,1,2,4,3,6,8,9,0,4,3,5,3,2,3,5,6,4,1,1,2,3)
my_vector

[1] 1 3 5 3 2 5 6 7 8 9 3 1 2 4 3 6 8 9 0 4 3 5 3 2 3 5 6 4 1 1 2 3

In [ ]:
# find length of vector
length(my_vector)

[1] 32



<br>




#### <font color=red>Task 4</font> (1 point)
* Multiply `matrix1` by `matrix2` below using scalar multiplication (use the `*` symbol)
* Print the result

In [ ]:
# matrices defined
matrix1 <- matrix(1:9, nrow=3)
matrix2 <- matrix(2:10, nrow=3)
matrix1
matrix2

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

[,1] [,2] [,3]
[1,] 2    5     8  
[2,] 3    6     9  
[3,] 4    7    10

In [ ]:
# multiply matrices
matrix1 * matrix2

[,1] [,2] [,3]
[1,]  2   20   56  
[2,]  6   30   72  
[3,] 12   42   90



<br>




#### <font color=red>Task 5</font> (1 point)
* Multiply `matrix1` by `matrix2` below using matrix multiplication (use the `%*%` symbol)
* Print the result

In [ ]:
# matrices defined
matrix1 <- matrix(1:9, nrow=3)
matrix2 <- matrix(2:10, nrow=3)
matrix1
matrix2

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

[,1] [,2] [,3]
[1,] 2    5     8  
[2,] 3    6     9  
[3,] 4    7    10

In [ ]:
# matrix multiplication
matrix1 %% matrix2

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9



<br>




## Collecting Data

#### <font color=red>Task 6</font> (4 points)

* Collect data from your other group members 
 * Name
 * Number of siblings
 * Pets ("Yes" or "No")
 * Name of one pet (if no pet, then use `NA`)
* Create 4 vectors for each of the variables (use variable names that are useful!)

If members of your group would not like to provide certain information, that is okay! Simply enter `NA` in their entry

In [ ]:
name <- c("Erin","Justin","Eunjin")
siblings <- c(2,2,1)
pets <- factor(c("yes", "yes", "no"))
petname <- c("tiny", "ellie","NA")


<br>

#### <font color=red>Task 7</font> (2 points)

* Bind the four vectors together into a dataframe
* Summarize your dataframe using `summary()`

In [ ]:
dat <- data.frame(name, siblings,pets,petname)
summary(dat)

     name              siblings      pets     petname         
 Length:3           Min.   :1.000   no :1   Length:3          
 Class :character   1st Qu.:1.500   yes:2   Class :character  
 Mode  :character   Median :2.000           Mode  :character  
                    Mean   :1.667                             
                    3rd Qu.:2.000                             
                    Max.   :2.000                             

<br>

#### <font color=red>Task 8</font> (1 point)

* Convert the Pets variable ("Yes" or "No") into a factor and store in your dataframe
* Use class to show it is now a `factor`

In [ ]:
pets_factor <- factor(pets)
pets_factor

[1] yes yes no 
Levels: no yes

<br>

#### <font color=red>Task 9</font> (1 point)

* Using your dataframe, calculate the average number of siblings in your group? (Use the `$` to call the variable from the dataframe)

In [ ]:
mean(siblings)

[1] 1.666667

## Dataframes

* R offers several built-in dataframes already loaded for you to use
* For this activity we will use the `mtcars` dataset containing information on different car models

* The goal of this portion of the lab is to create a new variable for this dataframe that represents the engine displacement per cylinder in cubic inches for each vehicle
* You may not know what displacement is (or maybe even cylinders), but it will suffice to know that values in the column named `disp` divided by values in the column named `cyl` will yield the appropriate quantity



<br>




#### <font color=red>Task 10</font> (1 point)

One fundamental principle of working with data is that you should never overwrite or change your original raw data
* Copy/Store the `mtcars` dataframe into another dataframe called `mtcars_lastname`
 * E.g., My dataframe would be `mtcars_hasenstab`

In [ ]:
mtcars_Park <- (mtcars)





<br>




#### <font color=red>Task 11</font> (1 point)

* View the first few lines of the dataframe using `head()`

In [ ]:
head(mtcars_Park)

mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2   
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1



<br>




#### <font color=red>Task 12</font> (1 point)

* Use R code to determine the number of rows (observations) and columns (variables) in the dataframe
* Print the result

In [ ]:
mtcars_Park <- (mtcars)
nrow(mtcars_Park)
ncol(mtcars_Park)


[1] 32

[1] 11



<br>




#### <font color=red>Task 13</font> (2 points)

* Calculate engine displacement per cylinder and save it as a new variable `UnitEngine` in the `mtcars_lastname` dataframe
* Note displacement per cylinder is defined by `disp` divided by `cyl`

Hint: `mt_cars$UnitEngine <- ...`

In [ ]:
 mtcars_Park$UnitEngine <- c(mtcars_Park$disp/mtcars_Park$cyl)





<br>




#### <font color=red>Task 14</font> (1 point)

* Confirm that the `UnitEngine` variable has been added to the `mtcars_lastname` dataframe using the `summary()` function
* Show the summary


In [ ]:
summary(mtcars_Park$UnitEngine)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  17.77   26.92   34.48   35.03   43.19   59.00 



<br>




#### <font color=red>Task 15</font> (1 point)

* Use the `mean()` function to calculate the average miles per gallon (`mpg`) of all of the cars in the dataset

In [ ]:
mean(mtcars_Park$mpg)

[1] 20.09062